name: ML Training & Testing Pipeline

# Trigger this workflow every time code is pushed to the main branch
on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # The cloud server OS
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run Training Script (Retrain Model)
      run: |
        python train.py
        
    - name: Run Model Tests (Verify Model)
      run: |
        python test_model.py
