name: ML Training & Testing Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run Training Script (Retrain Model)
      run: |
        python train.py
        
    - name: Run Model Tests (Verify Model)
      run: |
        python test_model.py
        
    - name: Save Model Artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-rf-model
        path: rf_model.pkl

    - name: Deploy to Hugging Face Space
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git remote add huggingface https://mayur020305:$HF_TOKEN@huggingface.co/spaces/mayur020305/My-First-Ml-App
        git push --force huggingface HEAD:main
